# https://docs.coderabbit.ai/configuration-options/
reviews:
  profile: assertive
  path_filters:
    - "!vendor/**"
    - "!build/**"
    - "!node_modules/**"
    - "!package-lock.json"
    - "!composer.lock"
