/**
 * Cloudflare Worker — WPPO Edge HTML Cache Adapter
 *
 * Deploys cache/wppo/{domain}/{path}/index.html semantics to the edge.
 * Stale-while-revalidate: serve cached HTML while revalidating origin in
 * the background. Mirrors the file cache layout so origin and edge share
 * the same URL space.
 *
 * Placeholders replaced by Edge_Cache::get_worker_js():
 *   {{ORIGIN_URL}} — e.g. https://example.com
 *   {{CACHE_TTL}}   — cache max-age seconds (e.g. 300)
 *   {{SWR}}         — stale-while-revalidate seconds (e.g. 86400)
 *
 * Deploy via wrangler.toml generated by Edge_Cache::get_wrangler_toml():
 *   wrangler deploy
 *
 * TTFB target: <30ms global (edge) vs LS-local ~90ms.
 *
 * @since NEXT
 */

export default {
  /**
   * Fetch handler with stale-while-revalidate.
   * @param {Request} request
   * @param {Object} env
   * @param {Object} ctx
   */
  async fetch(request, env, ctx) {
    // Only cache GET requests for HTML pages.
    if (request.method !== 'GET') {
      return fetch(request);
    }

    const url = new URL(request.url);

    // Bypass cache for query strings (search, ver, etc.) and non-HTML assets.
    if (url.search && /(?:^|&)(s|ver|v)(?:=|&|$)/.test(url.searchParams.toString())) {
      return fetch(request);
    }

    // Skip admin, preview, and non-cacheable paths.
    if (
      url.pathname.startsWith('/wp-admin') ||
      url.pathname.startsWith('/wp-login') ||
      url.pathname.includes('preview=true')
    ) {
      return fetch(request);
    }

    const cache = caches.default;
    const cacheKey = new Request(url.toString(), request);

    // Try edge cache first.
    let cachedResponse = await cache.match(cacheKey);

    if (cachedResponse) {
      // Revalidate in background — stale-while-revalidate = {{SWR}}s.
      ctx.waitUntil(
        (async () => {
          try {
            const originRes = await fetch(request);
            if (originRes.ok && originRes.headers.get('content-type')?.includes('text/html')) {
              const res = new Response(originRes.body, originRes);
              res.headers.set('Cache-Control', 'public, max-age={{CACHE_TTL}}, stale-while-revalidate={{SWR}}');
              res.headers.set('X-Edge-Cache', 'REVALIDATE');
              // Origin: {{ORIGIN_URL}}
              await cache.put(cacheKey, res.clone());
            }
          } catch (e) {
            // Swallow revalidation errors — stale remains.
          }
        })()
      );

      // Serve stale with SWR headers.
      const response = new Response(cachedResponse.body, cachedResponse);
      response.headers.set('Cache-Control', 'public, max-age={{CACHE_TTL}}, stale-while-revalidate={{SWR}}');
      response.headers.set('X-Edge-Cache', 'HIT');
      response.headers.set('X-WPPO-Edge', 'cloudflare');
      return response;
    }

    // Cache miss — fetch origin and populate edge cache.
    const originResponse = await fetch(request);

    // Only cache successful HTML responses.
    const contentType = originResponse.headers.get('content-type') || '';
    if (originResponse.ok && contentType.includes('text/html')) {
      const response = new Response(originResponse.body, originResponse);
      response.headers.set('Cache-Control', 'public, max-age={{CACHE_TTL}}, stale-while-revalidate={{SWR}}');
      response.headers.set('X-Edge-Cache', 'MISS');
      response.headers.set('X-WPPO-Edge', 'cloudflare');
      // Origin: {{ORIGIN_URL}}
      ctx.waitUntil(cache.put(cacheKey, response.clone()));
      return response;
    }

    return originResponse;
  },
};
