<?php
/**
 * Template for Performant Translations compiled PHP file.
 *
 * This file illustrates the structure generated by
 * `WP_Translation_File::transform( $mofile, 'php' )` and stored under
 * `wp-content/cache/wppo/lang/` (blog-scoped on multisite). It is not
 * loaded directly; `Perf_Translations::filter_load_file()` generates per-locale
 * files in that directory via `WP_Translation_File::transform()` when
 * `perf_translations.enabled` is true and `wp_cache_get_salted` exists.
 *
 * Example compiled file (`wp-content/cache/wppo/lang/my-plugin-de_DE-abc12345.l10n.php`):
 *
 *     <?php
 *     return [
 *         'domain'       => 'my-plugin',
 *         'language'     => 'de_DE',
 *         'plural-forms' => 'nplurals=2; plural=n != 1;',
 *         'messages'     => [
 *             'Hello' => ['Hallo'],
 *             'Post'  => ['Beitrag', 'Beiträge'],
 *         ],
 *     ];
 *
 * Core's `WP_Translation_File_PHP` then loads this array via `include` and
 * serves translations with OPCache acceleration.
 *
 * @package PerformanceOptimise\Inc
 * @since   NEXT
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Template illustration — actual files are generated dynamically.
return array(
	'plural-forms' => 'nplurals=2; plural=n != 1;',
	'messages'     => array(
		'Hello' => array( 'Hallo' ),
	),
);
