<?php
/**
 * Object Cache Manager.
 *
 * Handles Redis drop-in installation, removal, and testing.
 *
 * @package PerformanceOptimise
 */

namespace PerformanceOptimise\Inc;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Object_Cache
 *
 * @since 1.3.0
 */
class Object_Cache {

	/**
	 * Path to the object cache drop-in.
	 *
	 * @var string
	 */
	private $dropin_path;

	/**
	 * Path to the config file.
	 *
	 * @var string
	 */
	private $config_path;

	/**
	 * Path to the template file.
	 *
	 * @var string
	 */
	private $template_path;

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->dropin_path   = apply_filters( 'wppo_object_cache_dropin_path', WP_CONTENT_DIR . '/object-cache.php' );
		$this->config_path   = WP_CONTENT_DIR . '/wppo-redis-config.php';
		$this->template_path = WPPO_PLUGIN_PATH . 'templates/object-cache.php';
	}

	/**
	 * Get the status of the object cache.
	 *
	 * @return array Status information.
	 */
	public function get_status() {
		$status = array(
			'enabled'        => false,
			'redis_missing'  => ! class_exists( 'Redis' ),
			'foreign_dropin' => false,
		);

		if ( file_exists( $this->dropin_path ) ) {
			$wp_filesystem = Util::init_filesystem();

			if ( $wp_filesystem ) {
				$content = $wp_filesystem->get_contents( $this->dropin_path );
				if ( false !== strpos( $content, 'Redis Object Cache Drop-in for Performance Optimisation' ) ) {
					$status['enabled'] = true;
				} else {
					$status['foreign_dropin'] = true;
				}
			}
		}

		return $status;
	}

	/**
	 * Ping the Redis server to test connection.
	 *
	 * @param string $host Redis host.
	 * @param int    $port Redis port.
	 * @param string $password Redis password (optional).
	 * @param int    $database Redis Database ID.
	 * @return bool|\WP_Error True if connected, WP_Error on failure.
	 */
	public function ping( $host = '127.0.0.1', $port = 6379, $password = '', $database = 0 ) {
		if ( ! class_exists( 'Redis' ) ) {
			return new \WP_Error( 'missing_extension', 'The PhpRedis extension is not installed on this server.' );
		}

		try {
			$redis = new \Redis();
			if ( $redis->connect( $host, $port, 2.0 ) ) {
				if ( ! empty( $password ) ) {
					$redis->auth( $password );
				}
				$redis->select( $database );
				$redis->close();
				return true;
			}
		} catch ( \Exception $e ) {
			return new \WP_Error( 'redis_error', $e->getMessage() );
		}

		return new \WP_Error( 'connection_failed', 'Could not connect to Redis server.' );
	}

	/**
	 * Enable the Object Cache by writing the config and copying the drop-in.
	 *
	 * @param array $config Connection configuration.
	 * @return bool|\WP_Error True on success, WP_Error on failure.
	 */
	public function enable( $config ) {
		if ( ! class_exists( 'Redis' ) ) {
			return new \WP_Error( 'missing_extension', 'The PhpRedis extension is not installed.' );
		}

		$status = $this->get_status();
		if ( $status['foreign_dropin'] ) {
			return new \WP_Error( 'foreign_dropin', 'Another Object Cache drop-in is already present. Please disable it before enabling this one.' );
		}

		// Write config file safely without var_export.
		$host_str = esc_js( $config['host'] );
		$port_int = (int) $config['port'];
		$pass_str = esc_js( $config['password'] );
		$db_int   = (int) $config['database'];

		$config_content  = "<?php\n// Auto-generated by Performance Optimisation\n";
		$config_content .= "return array(\n";
		$config_content .= "\t'host'     => '{$host_str}',\n";
		$config_content .= "\t'port'     => {$port_int},\n";
		$config_content .= "\t'password' => '{$pass_str}',\n";
		$config_content .= "\t'database' => {$db_int},\n";
		$config_content .= ");\n";

		$wp_filesystem = Util::init_filesystem();

		if ( ! $wp_filesystem->put_contents( $this->config_path, $config_content, FS_CHMOD_FILE ) ) {
			return new \WP_Error( 'write_error', 'Cannot write configuration file to wp-content.' );
		}

		// Copy drop-in.
		if ( ! $wp_filesystem->copy( $this->template_path, $this->dropin_path, true, FS_CHMOD_FILE ) ) {
			$wp_filesystem->delete( $this->config_path );
			return new \WP_Error( 'write_error', 'Cannot copy object-cache.php drop-in to wp-content.' );
		}

		// Optionally, ping cache flush if enabled just to clear old cruft.
		wp_cache_flush();

		return true;
	}

	/**
	 * Disable the Object Cache by removing the drop-in and config.
	 *
	 * @return bool|\WP_Error True on success, WP_Error on failure.
	 */
	public function disable() {
		$status = $this->get_status();
		if ( $status['foreign_dropin'] ) {
			return new \WP_Error( 'foreign_dropin', 'A foreign drop-in exists. We will not delete it for safety.' );
		}

		$wp_filesystem = Util::init_filesystem();

		if ( file_exists( $this->dropin_path ) ) {
			if ( ! $wp_filesystem->delete( $this->dropin_path ) ) {
				return new \WP_Error( 'delete_error', 'Cannot delete object-cache.php from wp-content.' );
			}
		}

		if ( file_exists( $this->config_path ) ) {
			$wp_filesystem->delete( $this->config_path );
		}

		return true;
	}

	/**
	 * Flush the complete object cache.
	 *
	 * @return bool
	 */
	public function flush() {
		if ( function_exists( 'wp_cache_flush' ) ) {
			return wp_cache_flush();
		}
		return false;
	}
}
