name: Prepare Plugin for WordPress Submission on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  clean_up_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove .git, .gitignore, .github, and node_modules files
      run: |
        # Remove .git directory
        rm -rf .git
        # Remove .gitignore file
        rm -f .gitignore
        # Remove .github directory
        rm -rf .github
        # Remove node_modules directory
        rm -rf node_modules

    - name: Create zip file for WordPress submission
      run: |
        # Create a zip file for the plugin 'performance-optimisation' while excluding unnecessary files
        zip -r performance-optimisation.zip . -x ".git/*" ".gitignore" ".github/*" "node_modules/*"

    - name: Upload zip file as artifact (optional)
      uses: actions/upload-artifact@v3
      with:
        name: performance-optimisation
        path: performance-optimisation.zip
