name: Psalm and WPCS Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '28 13 * * 0'

permissions:
  contents: read
  issues: write  # Required for creating issues

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      issues: write  # Allow creating issues

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run WPCS check using 10up action and save output to file
      - name: Run WPCS check using 10up action and save output to file
        id: wpcs_check
        uses: 10up/wpcs-action@stable
        with:
          enable_warnings: true  # Set to true to check warnings
          paths: '.'  # Path to check, use '.' for the entire repository
          excludes: 'vendor src'  # Exclude these directories
          standard: 'WordPress'  # The WordPress standard you want to use
          phpcs_bin_path: 'phpcs'  # Path to the PHPCS binary
          use_local_config: 'false'  # If you want to use a local PHPCS config file
          extra_args: ''  # Any extra arguments you want to pass to PHPCS (e.g., '--severity=2')
          only_changed_files: 'false'  # Set to 'true' to check only changed files in the PR
          only_changed_lines: 'false'  # Set to 'true' to check only changed lines
        continue-on-error: true  # Continue even if this step fails

      # Step 3: Save WPCS check output to a file
      - name: Save WPCS check output to wpcs_report.txt
        if: failure()  # Only run this if the previous step failed (i.e., found issues)
        run: |
          echo "WPCS issues found. Saving output to wpcs_report.txt."
          echo "${{ steps.wpcs_check.outputs.stdout }}" > wpcs_report.txt

      # Step 4: Psalm Security Scan
      - name: Psalm Security Scan
        id: psalm
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287
        continue-on-error: true  # Continue the workflow even if Psalm fails

      # Step 5: Upload Security Analysis results to GitHub
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      # Step 6: Create GitHub issue if WPCS or Psalm errors are found
      - name: Create GitHub Issue on Errors
        if: failure()  # Only run this step if any previous step failed
        run: |
          # Create an issue with WPCS or Psalm errors
          body="### WPCS or Psalm errors detected in the codebase.\n\n"
          
          # Add WPCS errors to the issue body if they exist
          if [ -f wpcs_report.txt ]; then
            body+="#### WPCS Issues:\n\`\`\`\n$(cat wpcs_report.txt)\n\`\`\`\n"
          fi

          # Add Psalm errors to the issue body if they exist
          if [ -f results.sarif ]; then
            body+="#### Psalm Issues:\n\`\`\`\n$(cat results.sarif)\n\`\`\`\n"
          fi

          # Create a GitHub issue via GitHub API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "Code Quality Issues Found",
              "body": "'"${body}"'",
              "labels": ["bug", "wpcs", "security"]
            }' \
            https://api.github.com/repos/${{ github.repository }}/issues
