name: Remove Files on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  remove_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove .git, .gitignore, and .github
      run: |
        # Remove .git directory
        rm -rf .git

        # Remove .gitignore file
        rm -f .gitignore

        # Remove .github directory
        rm -rf .github

    - name: Commit changes after removal
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Remove .git, .gitignore, and .github files"
        git push origin --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
